# Generated by Django 3.2.3 on 2021-06-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_schedule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='detail',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
