# Generated by Django 3.2.3 on 2021-06-22 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notepad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepads',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notepads', to=settings.AUTH_USER_MODEL),
        ),
    ]
