# Generated by Django 3.2.3 on 2021-06-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0002_notepads_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepads',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
