# Generated by Django 3.2.3 on 2021-06-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0003_notepads_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notepads',
            options={'ordering': ['done', '-datetime_update']},
        ),
    ]
