# Generated by Django 3.2.3 on 2021-05-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('site_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.CharField(max_length=30)),
                ('sites', models.ManyToManyField(blank=True, related_name='site', to='sites.InputSite')),
            ],
        ),
    ]
